# Generated by Django 5.0.12 on 2025-03-14 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeesSynonym',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Employees_GO',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competencies',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('skill_level', models.IntegerField()),
            ],
            options={
                'db_table': 'competencies',
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('description', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evidence',
            },

        ),
        migrations.CreateModel(
            name='CompetencyRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('competency_name', models.ForeignKey(db_column='competency_name', on_delete=django.db.models.deletion.CASCADE, to='competency.competencies')),
            ],
            options={
                'db_table': 'competency_roles',
                'unique_together': {('competency_name', 'job_title')},
            },
        ),
    ]
